# Agent 5 — Safety Auditor Agent.
# Verifies Surviving Sepsis Campaign compliance, gives final approval before
# treatment is dispatched, writes the audit log entry, and generates a
# signed PDF audit report via the Nutrient Processor API.

import os
from datetime import datetime, timezone

from langchain_groq import ChatGroq
from pydantic import BaseModel, Field

from graph.state import SepsisGuardState
from models.schemas import TreatmentPlan
from prompts.auditor_prompt import SAFETY_AUDITOR_PROMPT
from tools.nutrient_tool import generate_pdf, sign_pdf

llm = ChatGroq(model="qwen/qwen3.8-27b", groq_api_key=os.getenv("GROQ_API_KEY"))


class ComplianceCheck(BaseModel):
    bundle_compliant: bool = Field(description="Whether the plan satisfies the Surviving Sepsis Campaign 1-hour bundle")
    violations: list[str] = Field(default_factory=list, description="Any compliance violations found")


structured_llm = llm.with_structured_output(ComplianceCheck)


STATUS_COLORS = {True: ("#22c55e", "#f0fdf4"), False: ("#ef4444", "#fef2f2")}


def _render_audit_html(state: SepsisGuardState, approved: bool, violations: list[str], audit_log: str) -> str:
    """Renders a polished, letterhead-style treatment plan + compliance audit as HTML for Nutrient to convert into a PDF."""
    patient_name = state.get("patient_name") or state.get("patient_id", "Unknown Patient")
    accent, tint = STATUS_COLORS[approved]
    status_label = "APPROVED" if approved else "REJECTED — REQUIRES REVIEW"

    violations_html = "".join(f"<li>{v}</li>" for v in violations) or "<li>None</li>"

    antibiotics = state.get("antibiotics", [])
    dosages = state.get("dosages", [])
    plan_rows = "".join(
        f"""<tr>
              <td class="drug">{abx}</td>
              <td>{dosages[i] if i < len(dosages) else '—'}</td>
            </tr>"""
        for i, abx in enumerate(antibiotics)
    ) or '<tr><td colspan="2" class="empty">No antibiotics recommended.</td></tr>'

    return f"""
    <html>
      <head>
        <style>
          * {{ box-sizing: border-box; }}
          body {{ font-family: 'Helvetica Neue', Arial, sans-serif; color: #1e293b; margin: 0; padding: 0; }}
          .header {{ background: linear-gradient(135deg, #0f172a, #1e3a5f); color: white; padding: 32px 40px; }}
          .header .brand {{ font-size: 13px; letter-spacing: 2px; text-transform: uppercase; color: #5eead4; font-weight: 600; }}
          .header h1 {{ margin: 6px 0 0; font-size: 24px; }}
          .header .sub {{ margin-top: 4px; color: #cbd5e1; font-size: 13px; }}
          .body {{ padding: 32px 40px; }}
          .info-grid {{ display: flex; gap: 24px; margin-bottom: 12px; }}
          .info-box {{ flex: 1; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px 16px; }}
          .info-box .label {{ font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #64748b; font-weight: 600; }}
          .info-box .value {{ font-size: 15px; font-weight: 700; margin-top: 2px; }}
          .status-banner {{ background: {tint}; border: 1px solid {accent}; border-left: 6px solid {accent}; border-radius: 8px; padding: 14px 18px; margin: 18px 0; }}
          .status-banner .status-label {{ color: {accent}; font-weight: 800; text-transform: uppercase; font-size: 14px; letter-spacing: 1px; }}
          h2 {{ font-size: 15px; color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-top: 28px; }}
          ul {{ margin: 10px 0; padding-left: 20px; font-size: 13px; line-height: 1.6; }}
          table {{ width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 13px; }}
          th {{ background: #0f172a; color: white; text-align: left; padding: 10px 12px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }}
          td {{ padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }}
          tr:nth-child(even) td {{ background: #f8fafc; }}
          td.drug {{ font-weight: 700; }}
          td.empty {{ text-align: center; color: #94a3b8; padding: 20px; }}
          .note-box {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; font-size: 13px; line-height: 1.6; margin-top: 10px; font-family: monospace; }}
          .footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; }}
        </style>
      </head>
      <body>
        <div class="header">
          <div class="brand">MediGuard &middot; SepsisGuard</div>
          <h1>Treatment Plan Audit Report</h1>
          <div class="sub">Generated by the SepsisGuard autonomous agent pipeline</div>
        </div>
        <div class="body">
          <div class="info-grid">
            <div class="info-box">
              <div class="label">Patient</div>
              <div class="value">{patient_name}</div>
            </div>
            <div class="info-box">
              <div class="label">Patient ID</div>
              <div class="value">{state.get('patient_id', '—')}</div>
            </div>
            <div class="info-box">
              <div class="label">Severity</div>
              <div class="value">{(state.get('severity') or '—').upper()}</div>
            </div>
          </div>

          <div class="status-banner">
            <div class="status-label">{status_label}</div>
          </div>

          <h2>Recommended Antibiotics &amp; Dosages</h2>
          <table>
            <thead><tr><th>Antibiotic</th><th>Dosage</th></tr></thead>
            <tbody>{plan_rows}</tbody>
          </table>

          <h2>ICU Resources</h2>
          <p style="font-size: 13px;">Bed: <strong>{state.get('bed_id') or '—'}</strong> &nbsp;|&nbsp; Infusion pump: <strong>{state.get('pump_id') or '—'}</strong></p>

          <h2>Compliance Violations</h2>
          <ul>{violations_html}</ul>

          <h2>Audit Log</h2>
          <div class="note-box">{audit_log}</div>

          <div class="footer">
            This report was generated by MediGuard's autonomous SepsisGuard pipeline and is intended to support,
            not replace, clinical judgment.
          </div>
        </div>
      </body>
    </html>
    """


def run(state: SepsisGuardState) -> SepsisGuardState:
    if not state.get("sepsis_alert"):
        return state

    check = structured_llm.invoke(
        [
            ("system", SAFETY_AUDITOR_PROMPT),
            (
                "human",
                f"Antibiotics: {state.get('antibiotics')}\n"
                f"Dosages: {state.get('dosages')}\n"
                f"Contraindication warnings: {state.get('contraindication_warnings')}\n"
                f"ICU bed reserved: {state.get('icu_bed_reserved')} ({state.get('bed_id')})\n"
                f"Infusion pump reserved: {state.get('infusion_pump_reserved')} ({state.get('pump_id')})",
            ),
        ]
    )

    approved = bool(
        check.bundle_compliant
        and not check.violations
        and state.get("icu_bed_reserved")
        and state.get("antibiotics")
    )

    audit_log = (
        f"[{datetime.now(timezone.utc).isoformat()}] Treatment plan for "
        f"{state.get('patient_id')} reviewed. Approved={approved}. "
        f"Violations={check.violations or 'none'}."
    )

    # Generate the audit PDF, then sign it. Either step can return None
    # (unconfigured key or a failed call) without raising — the pipeline
    # keeps running and the plan is still approved/rejected on its own
    # merits; only the PDF artifact is missing, flagged via a warning.
    signed_audit_pdf_base64 = None
    nutrient_warning = None
    audit_html = _render_audit_html(state, approved, check.violations, audit_log)
    unsigned_pdf_base64 = generate_pdf(audit_html)
    if unsigned_pdf_base64:
        signed_audit_pdf_base64 = sign_pdf(unsigned_pdf_base64)
        if not signed_audit_pdf_base64:
            nutrient_warning = "Nutrient generated the audit PDF but signing failed; using unsigned PDF."
            signed_audit_pdf_base64 = unsigned_pdf_base64
    else:
        nutrient_warning = "Nutrient PDF generation unavailable; audit report was not produced."

    treatment_plan = TreatmentPlan(
        patient_id=state["patient_id"],
        antibiotics=state.get("antibiotics", []),
        dosages=state.get("dosages", []),
        icu_bed_reserved=state.get("icu_bed_reserved", False),
        infusion_pump_reserved=state.get("infusion_pump_reserved", False),
        approved=approved,
        audit_log=audit_log,
    )

    return {
        **state,
        "approved": approved,
        "compliance_violations": check.violations,
        "audit_log": audit_log,
        "treatment_plan": treatment_plan.model_dump(),
        "signed_audit_pdf_base64": signed_audit_pdf_base64,
        "audit_pdf_signed": bool(signed_audit_pdf_base64) and nutrient_warning is None,
        "nutrient_warning": nutrient_warning,
    }
